### PR TITLE
Update all gridded data tutorial notebooks

### PR DESCRIPTION
**Pull request by spestana**
These should be the final versions of my notebooks. I will only be presenting notebooks 1, 2 and 3 (notebook 0 is just extra material). These notebooks were all developed and tested on the CUAHSI jupyterhub current image and environment as of 8/29.

### CODE REVIEW

**Comment by spestana** [comment]
environment.yml shouldn't be merged with this PR, my local copy was behind.

only the notebooks need to be merged

**Comment by emiliom** [comment]
@spestana I don't know how to "remove" a file from a PR on my end. I tried the "delete file" option under Files changed, but what that did is add a commit whose action is to delete the file, not remove the file-change action from the PR! To make matters worse, now the PR says that "This branch has conflicts that must be resolved". Trying to address this would be too complicated for me.

I'm closing the PR. Please submit it again. If you can remove the environment.yml file change from the PR, that'd be best. But if it's too much trouble, just resubmit as is and we'll see what happens. If I can merge, I'll do so, then update environment.yml

**Comment by emiliom** [comment]
FYI, if you just submit the same PR you submitted before, this post seems to have instructions on how to then "remove" a file from the PR, on your end:
https://ffeathers.wordpress.com/2020/03/21/removing-an-updated-file-from-a-pr-on-github/

**Comment by spestana** [comment]
Thanks for catching this. I tried those instructions but still ended up with a conflict on environment.yml when I start to make a new PR. It seems that there's a commit somewhere in my history that's causing the conflict?

I can try and revert to *before* any changes to that file were made, but that might be tricky to track down. Would it be easier to merge this PR, then replace the environment file if it indeed gets overwritten?

**Comment by emiliom** [comment]
> Would it be easier to merge this PR, then replace the environment file if it indeed gets overwritten?

That was my plan, but I can't merge the PR! It says there are conflicting files that must be resolved. I don't understand it.

I wonder if the conflict (or some of it) is due to the small changes to your notebooks that **I** inadvertently pushed a couple of weeks ago.

Only two possibilities come to mind, given my limited git expertise:
- The sledgehammer. I download your latest notebook files, drop them into a branch of my local clone and resolve conflicts there, then submit and merge a PR myself. All your recent git history (commit messages, etc) on those files will be lost. That's unfortunate, but probably not a big deal.
- I pull your branch from your fork into my local crone, then do the same as above. It's potentially more work, more stuff that could conflict, but the git history would be preserved.

Thoughts?

**Comment by spestana** [comment]
Whichever is easiest for you, is that the "sledgehammer"? Sorry to add to all the other work you're doing!
It is just the four notebook files that should be updated.

**Comment by emiliom** [comment]
The "sledge hammer" approach worked! Your notebooks are updated. Let me know if anything doesn't look right. I'm now closing this PR

**Pull request closed without merging**
